// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACWigNx6JaF4uHdhLRIJF4s3lBZWU-H3A',
    appId: '1:993848295802:web:3158532597f6eda5c296c3',
    messagingSenderId: '993848295802',
    projectId: 'e489final',
    authDomain: 'e489final.firebaseapp.com',
    storageBucket: 'e489final.firebasestorage.app',
    measurementId: 'G-H36TCVH9WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKIGdm3EywnFDK1RxJM_FR6lqhd3bwzEI',
    appId: '1:993848295802:android:dff1a767877977bdc296c3',
    messagingSenderId: '993848295802',
    projectId: 'e489final',
    storageBucket: 'e489final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj_NGDNts_KC4Bac3HPRNowbdWnu3oCAI',
    appId: '1:993848295802:ios:c5269e8975d5fec9c296c3',
    messagingSenderId: '993848295802',
    projectId: 'e489final',
    storageBucket: 'e489final.firebasestorage.app',
    iosBundleId: 'com.example.e489final',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj_NGDNts_KC4Bac3HPRNowbdWnu3oCAI',
    appId: '1:993848295802:ios:c5269e8975d5fec9c296c3',
    messagingSenderId: '993848295802',
    projectId: 'e489final',
    storageBucket: 'e489final.firebasestorage.app',
    iosBundleId: 'com.example.e489final',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACWigNx6JaF4uHdhLRIJF4s3lBZWU-H3A',
    appId: '1:993848295802:web:70004a3b39bcf5c7c296c3',
    messagingSenderId: '993848295802',
    projectId: 'e489final',
    authDomain: 'e489final.firebaseapp.com',
    storageBucket: 'e489final.firebasestorage.app',
    measurementId: 'G-VH5DDKE71X',
  );
}
